[package]
name = "cli_gui"
version = "0.1.0"
authors = ["luca <b.luca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
